### ISSUE TITLE
Execution failed for task ':generateProto'.

### ISSUE THREAD

**Issue by portLee** [jinho-yoo-jack/wanted-preonboarding-challenge-backend-25#4]
위 프로젝트를 클론해서 generateProto를 build하는 과정에서 해당 에러가 발생합니다. 해결방법을 찾아보고 있는데 어디가 문제인지 잘 모르겠네요...

> protoc: stdout: . stderr: --grpc_out: protoc-gen-grpc: The system cannot find the path specified.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 1s
3 actionable tasks: 1 executed, 2 up-to-date

**Comment by jinho-yoo-jack** [comment]
@portLee 혹시 gradle clean && gradle build 해보시겠어염...?!
그리고 grpc를 안쓰셔도 괜찮습니다!!

**Comment by portLee** [comment]
@jinho-yoo-jack clean && build 해봤는데도 똑같네요 ㅠㅠ.
안써도 괜찮군요! 감사합니다 ㅎㅎ

**Comment by jinho-yoo-jack** [comment]
@portLee  넵넵! 그리고 gRPC를 꼭 해보고 싶으시면..! 일단 JDK 버전이 21로 되어 있는지 확인이 필요할 것 같습니다>..<!

**Comment by portLee** [comment]
@jinho-yoo-jack JDK는 21버전으로 했습니다! gRPC를 써보고 싶긴한데 에러 이유를 모르겠네욥 ㅠㅠ

**Comment by jinho-yoo-jack** [comment]
@portLee  브랜치 목록에 보면 feature/jinho로 되어 있는 브랜치가 있는데 이걸로 받아서 한번 해보시겠어요?

**Comment by portLee** [comment]
@jinho-yoo-jack 해당 브랜치로 받아서 해봤는데 똑같네요 ㅠㅠ. 혹시 protoc.exe 파일을 별도로 다운을 받아야하는 걸까요??

**Comment by jinho-yoo-jack** [comment]
@portLee 아닙니다. 아래 블로그 한번 보시면서 따라 해보시겠어요?
- https://curiousjinan.tistory.com/entry/springboot3-grpc#7.%20gRPC%20%EC%82%AC%EC%9A%A9%ED%95%B4%20%EB%B3%B4%EA%B8%B0%20(%ED%81%B4%EB%9D%BC%EC%9D%B4%EC%96%B8%ED%8A%B8%EB%A5%BC%20%EC%82%AC%EC%9A%A9%ED%95%9C%20%EC%9A%94%EC%B2%AD)-1

**Comment by portLee** [comment]
@jinho-yoo-jack 감사합니다! 한번 해보도록 하겠습니다!

**Comment by portLee** [comment]
@jinho-yoo-jack 해당 에러 해결했습니다. 
사용자 계정이 한글로 되어 있어서 해당 경로를 못찾은 것 같습니다.. ㅎㅎ;;
