### ISSUE TITLE
질문드립니다! 

### ISSUE THREAD

**Issue by seongkyu-lim** [jinho-yoo-jack/wanted-preonboarding-challenge-backend-25#6]
사전과제 기간은 언제까지 인가요 ~?

**Comment by jinho-yoo-jack** [comment]
@seongkyu-lim  기한은 정해진 바는 없습니다. 다만, 수업이 진행되기 전까지 한번쯤 고민해보고 풀어보고 온다면 수업 참여율이 더 좋아질 수 있습니다.
