### ISSUE TITLE
[필수과제 1] 클래스 다이어그램 관련 질문드립니다.

### ISSUE THREAD

**Issue by elephant97** [jinho-yoo-jack/wanted-preonboarding-challenge-backend-25#7]
안녕하세요 멘토님,
필수과제 1번 항목 중 하나인 클래스 다이어그램 작성중에 있습니다.

<img width="1236" alt="스크린샷 2024-10-29 오후 10 39 42" src="https://github.com/user-attachments/assets/46d5b175-7899-4193-8dd4-6b90052ebb64">

다음과 같이 작성해 보았는데, 부족한 부분이 있는지 리뷰 받아볼 수 있을까요?
* 확장에 용이하도록 여러 PG사 클리언트를 팩토리 메서드 패턴으로 받아오도록 클래스다이어그램에 표현했습니다.
* 구현 시 팩토리 클래스에서 PG사에 맞는 클래스를 return 받을 수 있도록 기존에 생성되어있는 PgCrop enum 클래스에 각 PG사 별로 매핑되어야 하는 함수도 같이 캡슐화 할 예정입니다.
* 다른 응답값은 toss, nhn 응답값 비교 시 비슷한 구조가 아니라 응답값을 공통화 하기 위해 RequestDTO를 통해 제너릭 변수로 다른 응답값을 받아 return할 수 있도록 작성했습니다.

또한, 
완료되면 따로 제출하는 곳이 따로 있을까요? 
아니면 포크한 레포지토리의 README.md 내용 중 클래스 다이어그램 작성하기 부분에 체크표시 한 후 추가하려하는데 그렇게 하면 될까요?

**Comment by jinho-yoo-jack** [comment]
@elephant97 먼저 과제하시냐고 고생하셨습니다.

1. 확장에 용이하도록 여러 PG사 클리언트를 팩토리 메서드 패턴으로 받아오도록 클래스다이어그램에 표현했습니다.
- PgClient와 A-C PgClient 간의 관계도 이상하게 되어 있습니다! 클래스 다이어그램을 그리는 법 또한 한번 공부해보시고 다시 그려 보시면 좋을 것 같고 레이어 구분이 전혀 없습니다! 이 부분 또한 수정이 필요할 것으로 보여집니다.
2. 구현 시 팩토리 클래스에서 PG사에 맞는 클래스를 return 받을 수 있도록 기존에 생성되어있는 PgCrop enum 클래스에 각 PG사 별로 매핑되어야 하는 함수도 같이 캡슐화 할 예정입니다.
3. 다른 응답값은 toss, nhn 응답값 비교 시 비슷한 구조가 아니라 응답값을 공통화 하기 위해 RequestDTO를 통해 제너릭 변수로 다른 응답값을 받아 return할 수 있도록 작성했습니다.
- 제네릭 타입으로 한다고 하면, 결국에 프론트에서 각 PG사에 맞게 응답 메시지 처리를 다르게 해야하는데, 이러면 변경이 발생하면 프론트와 백엔드 2곳에서 모두 작업이 발생하는 문제가 있겠죠? 제네릭 타입이 아닌 다른 방법을 간구하는 것이 좋아 보입니다.

**Comment by jinho-yoo-jack** [comment]
@elephant97  아, 따로 제출하는 곳은 없고 리드미에 작성하셔도 되고 이슈로 과제를 제출해주셔도 무방합니다!!

**Comment by elephant97** [comment]
@jinho-yoo-jack 리뷰 감사합니다! 참고해서 수정해보도록 하겠습니다!

**Comment by elephant97** [comment]
@jinho-yoo-jack 멘토님 몇가지 더 여쭤보고 싶은 점이 있어 이슈 재 오픈 했습니다.    

리뷰해주신 내용 중

> 제네릭 타입으로 한다고 하면, 결국에 프론트에서 각 PG사에 맞게 응답 메시지 처리를 다르게 해야하는데, 이러면 변경이 발생하면 프론트와 백엔드 2곳에서 모두 작업이 발생하는 문제가 있겠죠? 제네릭 타입이 아닌 다른 방법을 간구하는 것이 좋아 보입니다.

해당 내용에서 '프론트에서 각 PG사에 맞게 응답 메시지 처리를 다르게 해야하는데, 이러면 변경이 발생하면 프론트와 백엔드 2곳에서 모두 작업이 발생하는 문제가 있다' 는 부분은 이해 했습니다.

근데 제가 생각하기로는 어떤 부분에 대해 공통화가 필요한지 헷갈립니다.

**1. nhn 결제 승인 요청 과정은 프론트에서 백엔드로 직접 결제 승인 요청을 보내지 않고 프론트 -> PG사 -> 백엔드 API 콜백 요청 데이터 RequestDto 공통화 필요**
   다음과 같이 이해했는데, 제가 결제 승인 요청 과정을 잘 못 이해한걸까요?       
   만일 이해한 내용이 맞다면 PG사에서 callback시 전달 해 주는 데이터를 RequestDto로 공통화 시켜야 하는 과정이 필요한지 궁금합니다.
   혹시 toss에서는 client에서 server로 결제정보를 넘겨주고, server가 PG사로  결제 승인 요청을 보내는 것으로 보이는데, 그 과정을 공통화 하는 것에 대해 말씀하신건가요?

<br>

**2. PG사에 결제 승인 요청 시 보내는 요청 데이터를 RequestDto 공통화 필요**
    PG사 마다 요청해야하는 응답 파라미터가 다른데, 이 내용을 공통화 하는 것이 과정이라면 리뷰주신 '프론트에서 PG사에 맞게 응답 메시지 처리를 다르게 해야하는데' 부분이 잘 이해가 되지 않습니다..   
    
<br>

   RequestDto가 아닌 ResponseDto라면 PG사마다 요청에 대한 승인 응답이 달라 공통화가 필요한 점은 인지하고 있으나, 웹 페이지 내에서 결제 요청 성공 시 보여주고 싶은 값이 정해져 있으므로 (예를 들면 주문 번호, 주문금액, 결제 성공 여부) 공통화가 아닌 PG사에서 return되는 응답 값 중 화면에 뿌려주고 싶은 데이터와 대응하는 값을 넣어주면 될 것 같고 PG사가 달라진다 해도 주문번호, 주문금액, 결제 성공 여부는 필수 값이라 PG사 변경에 따라 프론트에 리턴되는 값은 크게 영향받을 것 같지는 않다고 생각됩니다..

<br>

참고한 페이지는 다음과 같습니다.    
nhn: https://developer.kcp.co.kr/page/document/standardPay
toss: https://docs.tosspayments.com/guides/v2/payment-widget/integration

**Comment by jinho-yoo-jack** [comment]
@elephant97  아, 제가 잘못 전달했군요! ResponseMessage를 공통화 하는 것이 맞습니다..! 혼란을 드려 죄송합니다;;;
